-- AlterTable
ALTER TABLE `task` DROP COLUMN `completed`,
    ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN `status` ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING';
